@startuml
package "P Registrar Ministerios" #FFF2CC {
  class "FMinisterio" as fministerio {
  -MinisteriosController ministeriosController

  -DefaultTableModel modeloTabla
  --
  -actualizarTabla()
  -limpiarTabla(DefaultTableModel modelo)
  }
  class "MinisteriosController" as ctrministerio{
  -MinisteriosDAO ministeriosDAO
  -Ministerios ministerioPrototipo
  --
  +crearMinisterio(Ministerios ministerio): void
  +clone(): Ministerios
  +clonaryCrearMinisterios(): void
  +obtenerMinisterios(): List<Ministerios>
  }

  class "MinisteriosDAO" as daoministerios{
  --
  +agregarMinisterio(Ministerios ministerios)
  +obtenerMinisterios(): List<Ministerios>
  }

  class "BaseDAO" as daobase {
  --
  +obtenerConexion(): Connection
  +insertar(String tabla, Map<String, Object> campos): boolean
  +actualizar(String tabla, Map<String, Object> campos, String condicion): boolean
  +obtener(String tabla, String condicion, RowMapper<T> rowMapper): T
  +obtenerTodos(String tabla, RowMapper<T> rowMapper): List<T>
  +RowMapper<T>
  }
 class "ConexionBD" as bdconexion{
   -String CONFIG_FILE
   --
   +Connection establecerConexion()
  }
  entity "Ministerios" as ministerios{
      -String nombre
      -String descripcion
      --
      +Ministerios(String Nombre, String Descripcion)
      +Clone(): Ministerios
  }
  interface "Cloneable" as Prototype{
  --
  +Clone(): Ministerios
  }

  fministerio --> ctrministerio
  ctrministerio --> daoministerios
  daobase <|-- daoministerios : extends
  ctrministerio ..> ministerios
  daoministerios ..> ministerios
  daobase --> bdconexion
  Prototype<|.. ministerios : implements
  ctrministerio ..|> Prototype : implements
}


@enduml